M:init_screen
F:G$screen_init_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$screen_init_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Linit_screen.screen_init_screen_update$screen_type$1$28({2}DG,SC:U),B,1,4
T:Finit_screen$tag_struct_score_object[({0}S:S$score$0$0({2}SI:U),Z,0,0)({2}S:S$values$0$0({5}DA5d,SC:U),Z,0,0)({7}S:S$bonus$0$0({1}SC:U),Z,0,0)({8}S:S$candy$0$0({1}SC:U),Z,0,0)({9}S:S$oneup$0$0({1}SC:U),Z,0,0)]
S:G$global_score_object$0$0({10}STtag_struct_score_object:S),E,0,0
S:G$engine_asm_manager_clear_VRAM$0$0({2}DF,SV:S),C,0,0
S:G$engine_board_manager_border$0$0({2}DF,SV:S),C,0,0
S:G$engine_board_manager_toggle$0$0({2}DF,SV:S),C,0,0
S:G$engine_board_manager_side_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_board_manager_midd_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles_font$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles_game$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles_main$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles_splash$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_sprites_game$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_main_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_main_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_main_manager_save$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_pass$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_levels$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_option$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_debugging$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_get_candy$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_get_oneup$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_get_bonus$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_get_value$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_finish_bonus$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_bonus$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_candy$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_oneup$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_lives$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_boost$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_reset_lives$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_reset_boost$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
