M:audio_manager
F:G$engine_audio_manager_music_play$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Laudio_manager.engine_audio_manager_music_play$index$1$30({1}SC:U),B,1,4
S:Laudio_manager.engine_audio_manager_music_play$ho$1$31({2}DG,STtag_struct_hack_object:S),R,0,0,[]
S:Laudio_manager.engine_audio_manager_music_play$music_data$1$31({2}DG,SC:U),R,0,0,[c,b]
F:G$engine_audio_manager_music_play_norepeat$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Laudio_manager.engine_audio_manager_music_play_norepeat$index$1$33({1}SC:U),B,1,4
S:Laudio_manager.engine_audio_manager_music_play_norepeat$ho$1$34({2}DG,STtag_struct_hack_object:S),R,0,0,[]
S:Laudio_manager.engine_audio_manager_music_play_norepeat$music$1$34({2}DG,SC:U),R,0,0,[c,b]
S:Laudio_manager.engine_audio_manager_music_play_norepeat$bank$1$34({1}SC:U),R,0,0,[d]
F:G$engine_audio_manager_music_resume$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_audio_manager_music_stop$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_audio_manager_sfx_play$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Laudio_manager.engine_audio_manager_sfx_play$index$1$38({1}SC:U),B,1,4
S:Laudio_manager.engine_audio_manager_sfx_play$ho$1$39({2}DG,STtag_struct_hack_object:S),R,0,0,[]
S:Laudio_manager.engine_audio_manager_sfx_play$sfx$1$39({2}DG,SC:U),R,0,0,[c,b]
S:Laudio_manager.engine_audio_manager_sfx_play$status$1$39({1}SC:U),R,0,0,[l]
T:Faudio_manager$tag_struct_hack_object[({0}S:S$hack_object_delay_test$0$0({1}SC:U),Z,0,0)({1}S:S$hack_object_mydebugger$0$0({1}SC:U),Z,0,0)({2}S:S$hack_object_invincibie$0$0({1}SC:U),Z,0,0)({3}S:S$hack_object_full_boost$0$0({1}SC:U),Z,0,0)({4}S:S$hack_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$hack_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$hack_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$hack_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$hack_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$hack_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$hack_object_music_data$0$0({1}SC:U),Z,0,0)({11}S:S$hack_object_sound_data$0$0({1}SC:U),Z,0,0)({12}S:S$hack_object_enemy_move$0$0({3}DA3d,SC:U),Z,0,0)]
S:G$global_hack_object$0$0({15}STtag_struct_hack_object:S),E,0,0
S:G$sfx_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$music_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_tiles$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_color$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$locale_object_texts$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_AAdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_BBdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:Faudio_manager$music_bank$0$0({1}SC:U),E,0,0
S:G$engine_hack_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_invert$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PSGPlay$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGPlayNoRepeat$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGStop$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGResume$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGGetStatus$0$0({2}DF,SC:U),C,0,0
S:G$devkit_PSGSetMusicVolumeAttenuation$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXPlay$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXStop$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXGetStatus$0$0({2}DF,SC:U),C,0,0
S:G$devkit_PSGSilenceChannels$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGRestoreVolumes$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGFrame$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXFrame$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SFX_CHANNEL2$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SFX_CHANNEL3$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SFX_CHANNELS2AND3$0$0({2}DF,SC:U),C,0,0
