M:board_manager
F:G$engine_board_manager_border$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Lboard_manager.engine_board_manager_border$index$1$49({1}SC:U),B,1,4
S:Lboard_manager.engine_board_manager_border$st$1$50({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lboard_manager.engine_board_manager_border$type$1$50({1}SC:U),R,0,0,[b]
S:Lboard_manager.engine_board_manager_border$wide$1$50({1}SC:U),B,1,-1
S:Lboard_manager.engine_board_manager_border$rght$1$50({1}SC:U),R,0,0,[c]
S:Lboard_manager.engine_board_manager_border$left$1$50({1}SC:U),R,0,0,[c]
S:Lboard_manager.engine_board_manager_border$midd$1$50({1}SC:U),B,1,-2
S:Lboard_manager.engine_board_manager_border$loop$1$50({1}SC:U),R,0,0,[e]
F:G$engine_board_manager_toggle$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Lboard_manager.engine_board_manager_toggle$st$1$59({2}DG,STtag_struct_state_object:S),R,0,0,[c,b]
S:Lboard_manager.engine_board_manager_toggle$index$1$59({1}SC:U),R,0,0,[e]
S:Lboard_manager.engine_board_manager_toggle$x$1$59({1}SC:U),B,1,-4
S:Lboard_manager.engine_board_manager_toggle$y$1$59({1}SC:U),R,0,0,[d]
S:Lboard_manager.engine_board_manager_toggle$sloc0$1$0({2}DG,SC:U),B,1,-2
S:Lboard_manager.engine_board_manager_toggle$sloc1$1$0({1}SC:U),B,1,-3
F:G$engine_board_manager_side_tile$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_board_manager_midd_text$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lboard_manager.engine_board_manager_midd_text$st$1$65({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lboard_manager.engine_board_manager_midd_text$type$1$65({1}SC:U),R,0,0,[]
S:Lboard_manager.engine_board_manager_midd_text$loop$1$65({1}SC:U),R,0,0,[c]
T:Fboard_manager$tag_struct_state_object[({0}S:S$state_object_availables$0$0({1}SC:U),Z,0,0)({1}S:S$state_object_localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$state_object_high_score$0$0({2}SI:U),Z,0,0)({4}S:S$state_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$state_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$state_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$state_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$state_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$state_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$state_object_actor_kill$0$0({1}SC:U),Z,0,0)({11}S:S$state_object_fight_type$0$0({1}SC:U),Z,0,0)({12}S:S$state_object_curr_screen$0$0({1}SC:U),Z,0,0)({13}S:S$state_object_next_screen$0$0({1}SC:U),Z,0,0)]
S:G$global_state_object$0$0({14}STtag_struct_state_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertXYtoZ$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertZtoXY$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertByteToNibbles$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertNibblesToByte$0$0({2}DF,SV:S),C,0,0
S:G$engine_locale_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_fight$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_load_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_load_coll$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_blank$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_candy$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_trees$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_bonus$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_oneup$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_cross$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_sides$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_main_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_main_candy$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_main_gamer$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_funk_trees$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$_print_format$0$0({2}DF,SI:S),C,0,0
S:G$printf_small$0$0({2}DF,SV:S),C,0,0
S:G$printf$0$0({2}DF,SI:S),C,0,0
S:G$vprintf$0$0({2}DF,SI:S),C,0,0
S:G$sprintf$0$0({2}DF,SI:S),C,0,0
S:G$vsprintf$0$0({2}DF,SI:S),C,0,0
S:G$puts$0$0({2}DF,SI:S),C,0,0
S:G$gets$0$0({2}DF,DG,SC:U),C,0,0
S:G$getchar$0$0({2}DF,SC:U),C,0,0
S:G$putchar$0$0({2}DF,SI:S),C,0,0
