M:enemy_manager
F:G$engine_enemy_manager_init$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Lenemy_manager.engine_enemy_manager_init$eo$1$84({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
S:Lenemy_manager.engine_enemy_manager_init$frame$1$84({1}SC:U),R,0,0,[e]
S:Lenemy_manager.engine_enemy_manager_init$enemy$1$84({1}SC:U),B,1,-1
F:G$engine_enemy_manager_load$0$0({2}DF,SV:S),Z,0,8,0,0,0
S:Lenemy_manager.engine_enemy_manager_load$st$1$87({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_load$eo$1$87({2}DG,STtag_struct_enemy_object:S),B,1,-15
S:Lenemy_manager.engine_enemy_manager_load$enemy$1$87({1}SC:U),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_load$actor$1$87({1}SC:U),R,0,0,[c]
S:Lenemy_manager.engine_enemy_manager_load$check$1$87({1}SC:U),B,1,-19
S:Lenemy_manager.engine_enemy_manager_load$index$1$87({1}SC:U),B,1,-17
S:Lenemy_manager.engine_enemy_manager_load$count$1$87({1}SC:U),B,1,-16
S:Lenemy_manager.engine_enemy_manager_load$delta$1$87({1}SC:U),B,1,-18
S:Lenemy_manager.engine_enemy_manager_load$offset$1$87({1}SC:U),B,1,-20
S:Lenemy_manager.engine_enemy_manager_load$random$1$87({1}SC:U),B,1,-21
S:Lenemy_manager.engine_enemy_manager_load$sloc0$1$0({1}SC:U),B,1,-1
S:Lenemy_manager.engine_enemy_manager_load$sloc1$1$0({2}DG,DA4d,SC:U),B,1,-3
S:Lenemy_manager.engine_enemy_manager_load$sloc2$1$0({2}DG,DA2d,SC:U),B,1,-13
S:Lenemy_manager.engine_enemy_manager_load$sloc3$1$0({2}DC,SC:U),B,1,-11
S:Lenemy_manager.engine_enemy_manager_load$sloc4$1$0({2}DG,DA2d,SC:U),B,1,-9
S:Lenemy_manager.engine_enemy_manager_load$sloc5$1$0({2}DC,SC:U),B,1,-5
S:Lenemy_manager.engine_enemy_manager_load$sloc6$1$0({2}DG,DA2d,SC:U),B,1,-7
F:G$engine_enemy_manager_stance$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_stance$eo$1$99({2}DG,STtag_struct_enemy_object:S),R,0,0,[l,h]
S:Lenemy_manager.engine_enemy_manager_stance$enemy$1$99({1}SC:U),R,0,0,[b]
F:G$engine_enemy_manager_dohand$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_dohand$enemy$1$102({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_dohand$eo$1$103({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
F:G$engine_enemy_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_update$enemy$1$105({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_update$eo$1$106({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
S:Lenemy_manager.engine_enemy_manager_update$sloc0$1$0({2}DG,SC:U),B,1,-10
S:Lenemy_manager.engine_enemy_manager_update$sloc1$1$0({2}DG,SC:U),B,1,-2
S:Lenemy_manager.engine_enemy_manager_update$sloc2$1$0({2}DG,SC:U),B,1,-4
S:Lenemy_manager.engine_enemy_manager_update$sloc3$1$0({2}DG,SC:U),B,1,-6
S:Lenemy_manager.engine_enemy_manager_update$sloc4$1$0({2}DG,SC:U),B,1,-8
F:G$engine_enemy_manager_draw$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_draw$eo$1$118({2}DG,STtag_struct_enemy_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_draw$enemy$1$118({1}SC:U),R,0,0,[c]
F:G$engine_enemy_manager_draws$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_draws$enemy$1$121({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_draws$x$1$121({1}SC:U),B,1,5
S:Lenemy_manager.engine_enemy_manager_draws$y$1$121({1}SC:U),B,1,6
S:Lenemy_manager.engine_enemy_manager_draws$eo$1$122({2}DG,STtag_struct_enemy_object:S),R,0,0,[]
F:G$engine_enemy_manager_hide$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_hide$eo$1$123({2}DG,STtag_struct_enemy_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_hide$enemy$1$123({1}SC:U),R,0,0,[c]
F:G$engine_enemy_manager_move$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_move$enemy$1$127({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_move$direction$1$127({1}SC:U),B,1,5
S:Lenemy_manager.engine_enemy_manager_move$eo$1$128({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
F:G$engine_enemy_manager_pace$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_pace$enemy$1$129({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_pace$boost$1$129({1}SC:U),B,1,5
S:Lenemy_manager.engine_enemy_manager_pace$eo$1$130({2}DG,STtag_struct_enemy_object:S),R,0,0,[e,d]
S:Lenemy_manager.engine_enemy_manager_pace$sloc0$1$0({2}DG,SC:U),B,1,-2
F:G$engine_enemy_manager_stop$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_stop$enemy$1$131({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_stop$eo$1$132({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
F:G$engine_enemy_manager_dead$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_dead$enemy$1$133({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_dead$eo$1$134({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
F:G$engine_enemy_manager_reset_home$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_reset_home$eo$1$135({2}DG,STtag_struct_enemy_object:S),R,0,0,[e,d]
S:Lenemy_manager.engine_enemy_manager_reset_home$enemy$1$135({1}SC:U),R,0,0,[c]
F:G$engine_enemy_manager_reset_mode$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_reset_mode$enemy$1$138({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_reset_mode$mode$1$138({1}SC:U),B,1,5
S:Lenemy_manager.engine_enemy_manager_reset_mode$st$1$139({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_reset_mode$ho$1$139({2}DG,STtag_struct_hack_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_reset_mode$eo$1$139({2}DG,STtag_struct_enemy_object:S),R,0,0,[e,d]
S:Lenemy_manager.engine_enemy_manager_reset_mode$sloc0$1$0({2}DG,SC:U),B,1,-2
S:Lenemy_manager.engine_enemy_manager_reset_mode$sloc1$1$0({1}SC:U),B,1,-3
F:G$engine_enemy_manager_frame$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_frame$enemy$1$141({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_frame$eo$1$142({2}DG,STtag_struct_enemy_object:S),R,0,0,[l,h]
F:G$engine_enemy_manager_image$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_image$enemy$1$143({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_image$eo$1$144({2}DG,STtag_struct_enemy_object:S),R,0,0,[l,h]
F:G$engine_enemy_manager_images$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_images$image_pro$1$145({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_images$image_adi$1$145({1}SC:U),B,1,5
S:Lenemy_manager.engine_enemy_manager_images$image_suz$1$145({1}SC:U),B,1,6
F:G$engine_enemy_manager_debug$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_debug$ho$1$147({2}DG,STtag_struct_hack_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_debug$eo$1$147({2}DG,STtag_struct_enemy_object:S),R,0,0,[e,d]
S:Lenemy_manager.engine_enemy_manager_debug$enemy$1$147({1}SC:U),R,0,0,[c]
F:G$engine_enemy_manager_scatter_direction$0$0({2}DF,SC:U),Z,0,2,0,0,0
S:Lenemy_manager.engine_enemy_manager_scatter_direction$enemy$1$150({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_scatter_direction$eo$1$151({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
S:Lenemy_manager.engine_enemy_manager_scatter_direction$enemy_direction$1$151({1}SC:U),R,0,0,[l]
S:Lenemy_manager.engine_enemy_manager_scatter_direction$targetX$1$151({1}SC:U),B,1,-12
S:Lenemy_manager.engine_enemy_manager_scatter_direction$targetY$1$151({1}SC:U),B,1,-11
S:Lenemy_manager.engine_enemy_manager_scatter_direction$advance$1$151({1}SC:U),B,1,-6
S:Lenemy_manager.engine_enemy_manager_scatter_direction$actor$1$151({1}SC:U),R,0,0,[e]
S:Lenemy_manager.engine_enemy_manager_scatter_direction$sloc0$1$0({2}DG,DA4d,SC:U),B,1,-10
S:Lenemy_manager.engine_enemy_manager_scatter_direction$sloc1$1$0({1}SC:U),B,1,-6
S:Lenemy_manager.engine_enemy_manager_scatter_direction$sloc2$1$0({2}DG,SC:U),B,1,-2
S:Lenemy_manager.engine_enemy_manager_scatter_direction$sloc3$1$0({2}DG,SC:U),B,1,-5
S:Lenemy_manager.engine_enemy_manager_scatter_direction$sloc4$1$0({2}DG,SC:U),B,1,-8
S:Lenemy_manager.engine_enemy_manager_scatter_direction$sloc5$1$0({1}SC:U),B,1,-3
F:G$engine_enemy_manager_gohome_direction$0$0({2}DF,SC:U),Z,0,2,0,0,0
S:Lenemy_manager.engine_enemy_manager_gohome_direction$enemy$1$157({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_gohome_direction$eo$1$158({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
S:Lenemy_manager.engine_enemy_manager_gohome_direction$enemy_direction$1$158({1}SC:U),R,0,0,[l]
S:Lenemy_manager.engine_enemy_manager_gohome_direction$targetX$1$158({1}SC:U),B,1,-1
S:Lenemy_manager.engine_enemy_manager_gohome_direction$targetY$1$158({1}SC:U),B,1,-2
F:G$engine_enemy_manager_attack_direction$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lenemy_manager.engine_enemy_manager_attack_direction$enemy$1$160({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_attack_direction$targetX$1$160({1}SC:U),B,1,5
S:Lenemy_manager.engine_enemy_manager_attack_direction$targetY$1$160({1}SC:U),B,1,6
S:Lenemy_manager.engine_enemy_manager_attack_direction$eo$1$161({2}DG,STtag_struct_enemy_object:S),R,0,0,[e,d]
S:Lenemy_manager.engine_enemy_manager_attack_direction$eo0$1$161({2}DG,STtag_struct_enemy_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_attack_direction$enemy_direction$1$161({1}SC:U),B,1,-4
S:Lenemy_manager.engine_enemy_manager_attack_direction$sloc0$1$0({1}SC:U),B,1,-4
S:Lenemy_manager.engine_enemy_manager_attack_direction$sloc1$1$0({2}DG,SC:U),B,1,-3
S:Lenemy_manager.engine_enemy_manager_attack_direction$sloc2$1$0({1}SC:U),B,1,-1
S:Lenemy_manager.engine_enemy_manager_attack_direction$sloc3$1$0({2}DG,SC:U),B,1,-6
F:G$engine_enemy_manager_input_boost$0$0({2}DF,SC:U),Z,0,5,0,0,0
S:Lenemy_manager.engine_enemy_manager_input_boost$enemy$1$167({1}SC:U),B,1,4
S:Lenemy_manager.engine_enemy_manager_input_boost$st$1$168({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_input_boost$ho$1$168({2}DG,STtag_struct_hack_object:S),R,0,0,[]
S:Lenemy_manager.engine_enemy_manager_input_boost$eo$1$168({2}DG,STtag_struct_enemy_object:S),B,1,-9
S:Lenemy_manager.engine_enemy_manager_input_boost$toggle$1$168({1}SC:U),B,1,-11
S:Lenemy_manager.engine_enemy_manager_input_boost$boost$1$168({1}SC:U),B,1,-12
S:Lenemy_manager.engine_enemy_manager_input_boost$reset$1$168({1}SC:U),B,1,-10
S:Lenemy_manager.engine_enemy_manager_input_boost$sloc0$1$0({2}DG,SC:U),B,1,-4
S:Lenemy_manager.engine_enemy_manager_input_boost$sloc1$1$0({1}SC:U),B,1,-5
S:Lenemy_manager.engine_enemy_manager_input_boost$sloc2$1$0({2}DG,SC:U),B,1,-2
S:Lenemy_manager.engine_enemy_manager_input_boost$sloc3$1$0({2}DG,SC:U),B,1,-7
F:Fenemy_manager$calcd_frame$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.calcd_frame$enemy$1$173({1}SC:U),B,1,4
S:Lenemy_manager.calcd_frame$eo$1$174({2}DG,STtag_struct_enemy_object:S),R,0,0,[e,d]
F:Fenemy_manager$calcd_spots$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.calcd_spots$enemy$1$175({1}SC:U),B,1,4
S:Lenemy_manager.calcd_spots$eo$1$176({2}DG,STtag_struct_enemy_object:S),R,0,0,[c,b]
S:Lenemy_manager.calcd_spots$sloc0$1$0({2}DG,SC:U),B,1,-2
F:Fenemy_manager$calcd_image$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lenemy_manager.calcd_image$enemy$1$177({1}SC:U),B,1,4
S:Lenemy_manager.calcd_image$image$1$177({1}SC:U),B,1,5
S:Lenemy_manager.calcd_image$eo$1$178({2}DG,STtag_struct_enemy_object:S),R,0,0,[l,h]
T:Fenemy_manager$tag_struct_hack_object[({0}S:S$hack_object_delay_test$0$0({1}SC:U),Z,0,0)({1}S:S$hack_object_mydebugger$0$0({1}SC:U),Z,0,0)({2}S:S$hack_object_invincibie$0$0({1}SC:U),Z,0,0)({3}S:S$hack_object_full_boost$0$0({1}SC:U),Z,0,0)({4}S:S$hack_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$hack_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$hack_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$hack_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$hack_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$hack_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$hack_object_music_data$0$0({1}SC:U),Z,0,0)({11}S:S$hack_object_sound_data$0$0({1}SC:U),Z,0,0)({12}S:S$hack_object_enemy_move$0$0({3}DA3d,SC:U),Z,0,0)]
T:Fenemy_manager$tag_struct_level_object[({0}S:S$level_object_bonus_count$0$0({1}SC:U),Z,0,0)({1}S:S$level_object_candy_count$0$0({1}SC:U),Z,0,0)({2}S:S$level_object_oneup_count$0$0({1}SC:U),Z,0,0)({3}S:S$level_object_multiplier$0$0({1}SC:U),Z,0,0)]
T:Fenemy_manager$tag_struct_enemy_object[({0}S:S$posnX$0$0({1}SC:U),Z,0,0)({1}S:S$posnY$0$0({1}SC:U),Z,0,0)({2}S:S$tileX$0$0({1}SC:U),Z,0,0)({3}S:S$tileY$0$0({1}SC:U),Z,0,0)({4}S:S$tileZ$0$0({1}SC:U),Z,0,0)({5}S:S$waiter$0$0({1}SC:U),Z,0,0)({6}S:S$toggle$0$0({2}DA2d,SC:U),Z,0,0)({8}S:S$ticker$0$0({1}SC:U),Z,0,0)({9}S:S$action$0$0({1}SC:U),Z,0,0)({10}S:S$scatter$0$0({4}DA4d,SC:U),Z,0,0)({14}S:S$paths$0$0({1}SC:U),Z,0,0)({15}S:S$speeds$0$0({2}DA2d,SC:U),Z,0,0)({17}S:S$delays$0$0({2}DA2d,SC:U),Z,0,0)({19}S:S$speed$0$0({1}SC:U),Z,0,0)({20}S:S$delay$0$0({1}SC:U),Z,0,0)({21}S:S$timer$0$0({1}SC:U),Z,0,0)({22}S:S$total$0$0({1}SC:U),Z,0,0)({23}S:S$mover$0$0({1}SC:U),Z,0,0)({24}S:S$hands$0$0({1}SC:U),Z,0,0)({25}S:S$swaps$0$0({1}SC:U),Z,0,0)({26}S:S$loops$0$0({1}SC:U),Z,0,0)({27}S:S$lifecycle$0$0({1}SC:U),Z,0,0)({28}S:S$prev_move$0$0({1}SC:U),Z,0,0)({29}S:S$direction$0$0({1}SC:U),Z,0,0)({30}S:S$dir_count$0$0({1}SC:U),Z,0,0)({31}S:S$dir_total$0$0({1}SC:U),Z,0,0)({32}S:S$dir_total2$0$0({1}SC:U),Z,0,0)({33}S:S$image$0$0({1}SC:U),Z,0,0)({34}S:S$frame$0$0({1}SC:U),Z,0,0)({35}S:S$calcd$0$0({2}SI:U),Z,0,0)({37}S:S$images$0$0({4}DA2d,DA2d,SC:U),Z,0,0)]
T:Fenemy_manager$tag_struct_state_object[({0}S:S$state_object_availables$0$0({1}SC:U),Z,0,0)({1}S:S$state_object_localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$state_object_high_score$0$0({2}SI:U),Z,0,0)({4}S:S$state_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$state_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$state_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$state_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$state_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$state_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$state_object_actor_kill$0$0({1}SC:U),Z,0,0)({11}S:S$state_object_fight_type$0$0({1}SC:U),Z,0,0)({12}S:S$state_object_curr_screen$0$0({1}SC:U),Z,0,0)({13}S:S$state_object_next_screen$0$0({1}SC:U),Z,0,0)]
S:G$global_hack_object$0$0({15}STtag_struct_hack_object:S),E,0,0
S:G$level_object_tiles_array$0$0({0}DA0d,SC:U),E,0,0
S:G$global_level_object$0$0({4}STtag_struct_level_object:S),E,0,0
S:G$global_state_object$0$0({14}STtag_struct_state_object:S),E,0,0
S:G$music_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_tiles$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_color$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$locale_object_texts$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_AAdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_BBdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_enemy_objects$0$0({123}DA3d,STtag_struct_enemy_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertXYtoZ$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertZtoXY$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertByteToNibbles$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertNibblesToByte$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_invert$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_clear$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_load_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_temp_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_load_extra$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_directions$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_beat_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_blank_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_middle$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_get_collision$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_tile_type$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_next_tile$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_next_index$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_test_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_memo_manager_draw$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_pass$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_levels$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_option$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_debugging$0$0({2}DF,SV:S),C,0,0
S:G$engine_move_manager_get_directions$0$0({2}DF,SV:S),C,0,0
S:G$engine_move_manager_what_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_move_manager_gothru_exit$0$0({2}DF,SC:U),C,0,0
S:G$engine_move_manager_border_exit$0$0({2}DF,SC:U),C,0,0
S:G$engine_move_manager_inside_exit$0$0({2}DF,SC:U),C,0,0
S:G$engine_move_manager_opposite_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_sprite_manager_draw_entity$0$0({2}DF,SV:S),C,0,0
S:G$engine_sprite_manager_draw_boss1$0$0({2}DF,SV:S),C,0,0
S:G$engine_sprite_manager_draw_boss2$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_fight$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$atof$0$0({2}DF,SF:S),C,0,0
S:G$atoi$0$0({2}DF,SI:S),C,0,0
S:G$atol$0$0({2}DF,SL:S),C,0,0
S:G$_uitoa$0$0({2}DF,SV:S),C,0,0
S:G$_itoa$0$0({2}DF,SV:S),C,0,0
S:G$_ultoa$0$0({2}DF,SV:S),C,0,0
S:G$_ltoa$0$0({2}DF,SV:S),C,0,0
S:G$rand$0$0({2}DF,SI:S),C,0,0
S:G$srand$0$0({2}DF,SV:S),C,0,0
S:G$calloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$malloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$realloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$free$0$0({2}DF,SV:S),C,0,0
S:G$abs$0$0({2}DF,SI:S),C,0,0
S:G$labs$0$0({2}DF,SL:S),C,0,0
S:G$mblen$0$0({2}DF,SI:S),C,0,0
S:G$mbtowc$0$0({2}DF,SI:S),C,0,0
S:G$wctomb$0$0({2}DF,SI:S),C,0,0
S:G$mbstowcs$0$0({2}DF,SI:U),C,0,0
S:G$wcstombs$0$0({2}DF,SI:U),C,0,0
