M:font_manager
F:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_draw_char$ch$1$17({1}SC:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_char$x$1$17({1}SC:U),B,1,5
S:Lfont_manager.engine_font_manager_draw_char$y$1$17({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_char$pnt$1$18({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_char$tile$1$18({1}SC:U),R,0,0,[c]
F:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Lfont_manager.engine_font_manager_draw_text$text$1$19({2}DG,SC:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_text$x$1$19({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_text$y$1$19({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_text$pnt$1$20({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_text$idx$1$20({1}SC:U),B,1,-1
S:Lfont_manager.engine_font_manager_draw_text$tile$2$21({1}SC:S),R,0,0,[b]
F:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Lfont_manager.engine_font_manager_draw_data$data$1$22({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_data$x$1$22({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_data$y$1$22({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_data$pnt$1$23({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_data$idx$1$23({1}SC:U),B,1,-2
S:Lfont_manager.engine_font_manager_draw_data$tile$1$23({1}SC:S),R,0,0,[c]
S:Lfont_manager.engine_font_manager_draw_data$quotient$1$23({2}SI:U),R,0,0,[e,d]
S:Lfont_manager.engine_font_manager_draw_data$remainder$1$23({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_draw_data$sloc0$1$0({1}SC:U),B,1,-1
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
