M:function_manager
F:G$engine_function_manager_convertXYtoZ$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertXYtoZ$divide$1$18({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertXYtoZ$x$1$18({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertXYtoZ$y$1$18({1}SC:U),B,1,6
S:Lfunction_manager.engine_function_manager_convertXYtoZ$z$1$18({2}DG,SC:U),B,1,7
F:G$engine_function_manager_convertZtoXY$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertZtoXY$divide$1$20({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertZtoXY$z$1$20({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertZtoXY$x$1$20({2}DG,SC:U),B,1,6
S:Lfunction_manager.engine_function_manager_convertZtoXY$y$1$20({2}DG,SC:U),B,1,8
F:G$engine_function_manager_convertByteToNibbles$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$byte$1$22({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$upper_nibble$1$22({2}DG,SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$lower_nibble$1$22({2}DG,SC:U),B,1,7
F:G$engine_function_manager_convertNibblesToByte$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$upper_nibble$1$24({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$lower_nibble$1$24({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$byte$1$24({2}DG,SC:U),B,1,6
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
