M:level_manager
F:G$engine_level_manager_clear$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_clear$row$1$70({1}SC:U),R,0,0,[b]
S:Llevel_manager.engine_level_manager_clear$col$1$70({1}SC:U),R,0,0,[e]
S:Llevel_manager.engine_level_manager_clear$index$1$70({1}SC:U),R,0,0,[l]
F:G$engine_level_manager_load_level$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Llevel_manager.engine_level_manager_load_level$world$1$75({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_load_level$round$1$75({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_load_level$halve$1$76({1}SC:U),R,0,0,[]
S:Llevel_manager.engine_level_manager_load_level$level$1$76({1}SC:U),R,0,0,[c]
S:Llevel_manager.engine_level_manager_load_level$index$1$76({1}SC:U),R,0,0,[c]
S:Llevel_manager.engine_level_manager_load_level$mult$1$76({1}SC:U),B,1,-1
S:Llevel_manager.engine_level_manager_load_level$data$2$79({2}DG,SC:U),R,0,0,[e,d]
S:Llevel_manager.engine_level_manager_load_level$size$2$79({1}SC:U),R,0,0,[b]
S:Llevel_manager.engine_level_manager_load_level$bank$2$79({1}SC:U),R,0,0,[c]
S:Llevel_manager.engine_level_manager_load_level$data$2$80({2}DG,SC:U),R,0,0,[e,d]
S:Llevel_manager.engine_level_manager_load_level$size$2$80({1}SC:U),R,0,0,[b]
S:Llevel_manager.engine_level_manager_load_level$bank$2$80({1}SC:U),R,0,0,[c]
F:G$engine_level_manager_temp_level$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_temp_level$tileX$1$81({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_temp_level$tileY$1$81({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_temp_level$tile_type$1$81({1}SC:U),B,1,6
S:Llevel_manager.engine_level_manager_temp_level$lo$1$82({2}DG,STtag_struct_level_object:S),R,0,0,[]
S:Llevel_manager.engine_level_manager_temp_level$row$1$82({1}SC:U),R,0,0,[b]
S:Llevel_manager.engine_level_manager_temp_level$col$1$82({1}SC:U),R,0,0,[e]
S:Llevel_manager.engine_level_manager_temp_level$index$1$82({1}SC:U),R,0,0,[l]
F:G$engine_level_manager_load_extra$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Llevel_manager.engine_level_manager_load_extra$quantity$1$87({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_load_extra$tile_type$1$87({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_load_extra$lo$1$88({2}DG,STtag_struct_level_object:S),R,0,0,[]
S:Llevel_manager.engine_level_manager_load_extra$row$1$88({1}SC:U),R,0,0,[e]
S:Llevel_manager.engine_level_manager_load_extra$col$1$88({1}SC:U),B,1,-4
S:Llevel_manager.engine_level_manager_load_extra$index$1$88({1}SC:U),R,0,0,[l]
S:Llevel_manager.engine_level_manager_load_extra$tiles$1$88({1}SC:U),R,0,0,[]
S:Llevel_manager.engine_level_manager_load_extra$loops$1$88({1}SC:U),R,0,0,[d]
S:Llevel_manager.engine_level_manager_load_extra$sloc0$1$0({1}SC:U),B,1,-1
S:Llevel_manager.engine_level_manager_load_extra$sloc1$1$0({2}SI:S),B,1,-3
F:G$engine_level_manager_directions$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Llevel_manager.engine_level_manager_directions$row$1$94({1}SC:U),R,0,0,[c]
S:Llevel_manager.engine_level_manager_directions$col$1$94({1}SC:U),R,0,0,[b]
S:Llevel_manager.engine_level_manager_directions$index$1$94({2}SI:U),R,0,0,[e,d]
S:Llevel_manager.engine_level_manager_directions$test_type$1$94({1}SC:U),B,1,-2
S:Llevel_manager.engine_level_manager_directions$direction$1$94({1}SC:U),B,1,-3
S:Llevel_manager.engine_level_manager_directions$sloc0$1$0({1}SC:U),B,1,-1
F:G$engine_level_manager_draw_level$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_draw_level$row$1$99({1}SC:U),R,0,0,[b]
S:Llevel_manager.engine_level_manager_draw_level$col$1$99({1}SC:U),R,0,0,[d]
F:G$engine_level_manager_draw_middle$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_draw_middle$row$1$105({1}SC:U),R,0,0,[c]
S:Llevel_manager.engine_level_manager_draw_middle$col$1$105({1}SC:U),R,0,0,[b]
F:G$engine_level_manager_beat_level$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_beat_level$data$1$110({2}DG,SC:U),B,1,4
S:Llevel_manager.engine_level_manager_beat_level$size$1$110({1}SC:U),B,1,6
S:Llevel_manager.engine_level_manager_beat_level$bank$1$110({1}SC:U),B,1,7
F:G$engine_level_manager_blank_tile$0$0({2}DF,SV:S),Z,0,3,0,0,0
S:Llevel_manager.engine_level_manager_blank_tile$index$1$112({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_blank_tile$upper_nibble$1$113({1}SC:U),B,1,-3
S:Llevel_manager.engine_level_manager_blank_tile$lower_nibble$1$113({1}SC:U),B,1,-4
S:Llevel_manager.engine_level_manager_blank_tile$tile_type$1$113({1}SC:U),B,1,-5
S:Llevel_manager.engine_level_manager_blank_tile$sloc0$1$0({2}DD,SC:U),B,1,-2
F:G$engine_level_manager_get_collision$0$0({2}DF,SC:U),Z,0,2,0,0,0
S:Llevel_manager.engine_level_manager_get_collision$x$1$114({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_get_collision$y$1$114({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_get_collision$direction$1$114({1}SC:U),B,1,6
S:Llevel_manager.engine_level_manager_get_collision$offset$1$114({1}SC:U),B,1,7
S:Llevel_manager.engine_level_manager_get_collision$collision$1$115({1}SC:U),R,0,0,[l]
S:Llevel_manager.engine_level_manager_get_collision$upper_nibble$1$115({1}SC:U),B,1,-1
S:Llevel_manager.engine_level_manager_get_collision$lower_nibble$1$115({1}SC:U),B,1,-2
S:Llevel_manager.engine_level_manager_get_collision$tile$1$115({1}SC:U),R,0,0,[b]
F:G$engine_level_manager_get_direction$0$0({2}DF,SC:U),Z,0,2,0,0,0
S:Llevel_manager.engine_level_manager_get_direction$x$1$116({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_get_direction$y$1$116({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_get_direction$direction$1$116({1}SC:U),B,1,6
S:Llevel_manager.engine_level_manager_get_direction$offset$1$116({1}SC:U),B,1,7
S:Llevel_manager.engine_level_manager_get_direction$upper_nibble$1$117({1}SC:U),B,1,-1
S:Llevel_manager.engine_level_manager_get_direction$lower_nibble$1$117({1}SC:U),B,1,-2
S:Llevel_manager.engine_level_manager_get_direction$tile$1$117({1}SC:U),R,0,0,[b]
F:G$engine_level_manager_get_tile_type$0$0({2}DF,SC:U),Z,0,2,0,0,0
S:Llevel_manager.engine_level_manager_get_tile_type$x$1$118({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_get_tile_type$y$1$118({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_get_tile_type$direction$1$118({1}SC:U),B,1,6
S:Llevel_manager.engine_level_manager_get_tile_type$offset$1$118({1}SC:U),B,1,7
S:Llevel_manager.engine_level_manager_get_tile_type$tile_type$1$119({1}SC:U),R,0,0,[l]
S:Llevel_manager.engine_level_manager_get_tile_type$upper_nibble$1$119({1}SC:U),B,1,-2
S:Llevel_manager.engine_level_manager_get_tile_type$lower_nibble$1$119({1}SC:U),B,1,-1
S:Llevel_manager.engine_level_manager_get_tile_type$tile$1$119({1}SC:U),R,0,0,[b]
F:G$engine_level_manager_get_next_tile$0$0({2}DF,SC:U),Z,0,1,0,0,0
S:Llevel_manager.engine_level_manager_get_next_tile$x$1$121({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_get_next_tile$y$1$121({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_get_next_tile$direction$1$121({1}SC:U),B,1,6
S:Llevel_manager.engine_level_manager_get_next_tile$offset$1$121({1}SC:U),B,1,7
S:Llevel_manager.engine_level_manager_get_next_tile$index$1$122({1}SC:U),B,1,-1
F:G$engine_level_manager_get_next_index$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_get_next_index$x$1$127({2}DG,SC:U),B,1,4
S:Llevel_manager.engine_level_manager_get_next_index$y$1$127({2}DG,SC:U),B,1,6
S:Llevel_manager.engine_level_manager_get_next_index$direction$1$127({1}SC:U),B,1,8
S:Llevel_manager.engine_level_manager_get_next_index$offset$1$127({1}SC:S),B,1,9
F:G$engine_level_manager_test_direction$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_test_direction$row$1$133({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_test_direction$col$1$133({1}SC:U),B,1,5
S:Llevel_manager.engine_level_manager_test_direction$direction_type$1$134({1}SC:U),R,0,0,[c]
S:Llevel_manager.engine_level_manager_test_direction$test_type$2$135({1}SC:U),R,0,0,[c]
S:Llevel_manager.engine_level_manager_test_direction$test_type$2$136({1}SC:U),R,0,0,[l]
S:Llevel_manager.engine_level_manager_test_direction$test_type$2$137({1}SC:U),R,0,0,[l]
S:Llevel_manager.engine_level_manager_test_direction$test_type$2$138({1}SC:U),R,0,0,[l]
F:Flevel_manager$load_level$0$0({2}DF,SV:S),Z,0,6,0,0,0
S:Llevel_manager.load_level$data$1$139({2}DG,SC:U),B,1,4
S:Llevel_manager.load_level$size$1$139({1}SC:U),B,1,6
S:Llevel_manager.load_level$bank$1$139({1}SC:U),B,1,7
S:Llevel_manager.load_level$mult$1$139({1}SC:U),B,1,8
S:Llevel_manager.load_level$lo$1$140({2}DG,STtag_struct_level_object:S),R,0,0,[]
S:Llevel_manager.load_level$o$1$140({2}DG,SC:U),R,0,0,[c,b]
S:Llevel_manager.load_level$row$1$140({1}SC:U),B,1,-6
S:Llevel_manager.load_level$col$1$140({1}SC:U),B,1,-5
S:Llevel_manager.load_level$tile_data$1$140({1}SC:U),B,1,-8
S:Llevel_manager.load_level$index$1$140({1}SC:U),R,0,0,[e]
S:Llevel_manager.load_level$tile_type$1$140({1}SC:U),B,1,-4
S:Llevel_manager.load_level$coll_type$1$140({1}SC:U),B,1,-7
S:Llevel_manager.load_level$load_cols$1$140({1}SC:U),B,1,-9
S:Llevel_manager.load_level$draw_cols$1$140({1}SC:U),R,0,0,[]
S:Llevel_manager.load_level$sloc0$1$0({1}SC:U),B,1,-3
S:Llevel_manager.load_level$sloc1$1$0({2}DG,SC:U),B,1,-2
F:Flevel_manager$draw_tiles$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.draw_tiles$x$1$149({1}SC:U),B,1,4
S:Llevel_manager.draw_tiles$y$1$149({1}SC:U),B,1,5
S:Llevel_manager.draw_tiles$lo$1$150({2}DG,STtag_struct_level_object:S),R,0,0,[]
S:Llevel_manager.draw_tiles$index$1$150({1}SC:U),R,0,0,[c]
S:Llevel_manager.draw_tiles$tile$1$150({1}SC:U),R,0,0,[c]
F:Flevel_manager$test_direction$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Llevel_manager.test_direction$x$1$151({1}SC:U),B,1,4
S:Llevel_manager.test_direction$y$1$151({1}SC:U),B,1,5
S:Llevel_manager.test_direction$input_direction$1$151({1}SC:U),B,1,6
S:Llevel_manager.test_direction$index$1$152({1}SC:U),R,0,0,[b]
S:Llevel_manager.test_direction$tile$1$152({1}SC:U),R,0,0,[]
S:Llevel_manager.test_direction$coll$1$152({1}SC:U),R,0,0,[]
S:Llevel_manager.test_direction$test_type$1$152({1}SC:U),R,0,0,[c]
T:Flevel_manager$tag_struct_level_object[({0}S:S$level_object_bonus_count$0$0({1}SC:U),Z,0,0)({1}S:S$level_object_candy_count$0$0({1}SC:U),Z,0,0)({2}S:S$level_object_oneup_count$0$0({1}SC:U),Z,0,0)({3}S:S$level_object_multiplier$0$0({1}SC:U),Z,0,0)]
T:Flevel_manager$tag_struct_state_object[({0}S:S$state_object_availables$0$0({1}SC:U),Z,0,0)({1}S:S$state_object_localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$state_object_high_score$0$0({2}SI:U),Z,0,0)({4}S:S$state_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$state_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$state_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$state_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$state_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$state_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$state_object_actor_kill$0$0({1}SC:U),Z,0,0)({11}S:S$state_object_fight_type$0$0({1}SC:U),Z,0,0)({12}S:S$state_object_curr_screen$0$0({1}SC:U),Z,0,0)({13}S:S$state_object_next_screen$0$0({1}SC:U),Z,0,0)]
S:G$level_object_tiles_array$0$0({0}DA0d,SC:U),E,0,0
S:G$global_state_object$0$0({14}STtag_struct_state_object:S),E,0,0
S:G$music_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_tiles$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_color$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$locale_object_texts$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_AAdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_BBdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_level_object$0$0({4}STtag_struct_level_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertXYtoZ$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertZtoXY$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertByteToNibbles$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertNibblesToByte$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_fight$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_load_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_load_coll$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_blank$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_candy$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_trees$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_bonus$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_oneup$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_cross$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_sides$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_main_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_main_candy$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_main_gamer$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_funk_trees$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$atof$0$0({2}DF,SF:S),C,0,0
S:G$atoi$0$0({2}DF,SI:S),C,0,0
S:G$atol$0$0({2}DF,SL:S),C,0,0
S:G$_uitoa$0$0({2}DF,SV:S),C,0,0
S:G$_itoa$0$0({2}DF,SV:S),C,0,0
S:G$_ultoa$0$0({2}DF,SV:S),C,0,0
S:G$_ltoa$0$0({2}DF,SV:S),C,0,0
S:G$rand$0$0({2}DF,SI:S),C,0,0
S:G$srand$0$0({2}DF,SV:S),C,0,0
S:G$calloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$malloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$realloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$free$0$0({2}DF,SV:S),C,0,0
S:G$abs$0$0({2}DF,SI:S),C,0,0
S:G$labs$0$0({2}DF,SL:S),C,0,0
S:G$mblen$0$0({2}DF,SI:S),C,0,0
S:G$mbtowc$0$0({2}DF,SI:S),C,0,0
S:G$wctomb$0$0({2}DF,SI:S),C,0,0
S:G$mbstowcs$0$0({2}DF,SI:U),C,0,0
S:G$wcstombs$0$0({2}DF,SI:U),C,0,0
