M:memo_manager
F:G$engine_memo_manager_draw$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lmemo_manager.engine_memo_manager_draw$topIndex$1$28({1}SC:U),B,1,4
S:Lmemo_manager.engine_memo_manager_draw$botIndex$1$28({1}SC:U),B,1,5
S:Lmemo_manager.engine_memo_manager_draw$x$1$29({1}SC:U),R,0,0,[]
S:Lmemo_manager.engine_memo_manager_draw$y$1$29({1}SC:U),R,0,0,[]
F:G$engine_memo_manager_pass$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lmemo_manager.engine_memo_manager_pass$perfect$1$30({1}SC:U),B,1,4
S:Lmemo_manager.engine_memo_manager_pass$topIndex$1$31({1}SC:U),R,0,0,[]
S:Lmemo_manager.engine_memo_manager_pass$botIndex$1$31({1}SC:U),R,0,0,[b]
F:G$engine_memo_manager_levels$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lmemo_manager.engine_memo_manager_levels$x$1$33({1}SC:U),B,1,4
S:Lmemo_manager.engine_memo_manager_levels$y1$1$33({1}SC:U),B,1,5
S:Lmemo_manager.engine_memo_manager_levels$y2$1$33({1}SC:U),B,1,6
S:Lmemo_manager.engine_memo_manager_levels$st$1$34({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:G$engine_memo_manager_option$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Lmemo_manager.engine_memo_manager_option$st$1$35({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lmemo_manager.engine_memo_manager_option$text$1$35({2}DG,SC:U),B,1,-6
S:Lmemo_manager.engine_memo_manager_option$x$1$35({1}SC:U),R,0,0,[]
S:Lmemo_manager.engine_memo_manager_option$sloc0$1$0({1}SC:U),B,1,-4
S:Lmemo_manager.engine_memo_manager_option$sloc1$1$0({1}SC:U),B,1,-1
S:Lmemo_manager.engine_memo_manager_option$sloc2$1$0({2}SI:S),B,1,-3
F:G$engine_memo_manager_debugging$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Lmemo_manager.engine_memo_manager_debugging$enemy$1$40({1}SC:U),B,1,4
S:Lmemo_manager.engine_memo_manager_debugging$action$1$40({1}SC:U),B,1,5
S:Lmemo_manager.engine_memo_manager_debugging$x$1$41({1}SC:U),R,0,0,[d]
S:Lmemo_manager.engine_memo_manager_debugging$y$1$41({1}SC:U),R,0,0,[]
S:Lmemo_manager.engine_memo_manager_debugging$text$1$41({4}DA4d,SC:U),B,1,-4
T:Fmemo_manager$tag_struct_score_object[({0}S:S$score$0$0({2}SI:U),Z,0,0)({2}S:S$values$0$0({5}DA5d,SC:U),Z,0,0)({7}S:S$bonus$0$0({1}SC:U),Z,0,0)({8}S:S$candy$0$0({1}SC:U),Z,0,0)({9}S:S$oneup$0$0({1}SC:U),Z,0,0)]
T:Fmemo_manager$tag_struct_state_object[({0}S:S$state_object_availables$0$0({1}SC:U),Z,0,0)({1}S:S$state_object_localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$state_object_high_score$0$0({2}SI:U),Z,0,0)({4}S:S$state_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$state_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$state_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$state_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$state_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$state_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$state_object_actor_kill$0$0({1}SC:U),Z,0,0)({11}S:S$state_object_fight_type$0$0({1}SC:U),Z,0,0)({12}S:S$state_object_curr_screen$0$0({1}SC:U),Z,0,0)({13}S:S$state_object_next_screen$0$0({1}SC:U),Z,0,0)]
S:G$global_score_object$0$0({10}STtag_struct_score_object:S),E,0,0
S:G$global_state_object$0$0({14}STtag_struct_state_object:S),E,0,0
S:G$locale_object_number$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$music_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_tiles$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_color$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$locale_object_texts$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_AAdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_BBdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$engine_board_manager_border$0$0({2}DF,SV:S),C,0,0
S:G$engine_board_manager_toggle$0$0({2}DF,SV:S),C,0,0
S:G$engine_board_manager_side_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_board_manager_midd_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_locale_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_get_candy$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_get_oneup$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_get_bonus$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_get_value$0$0({2}DF,SC:U),C,0,0
S:G$engine_score_manager_finish_bonus$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_bonus$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_candy$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_oneup$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_lives$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_boost$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_reset_lives$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_reset_boost$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_fight$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
