M:move_manager
F:G$engine_move_manager_get_directions$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Lmove_manager.engine_move_manager_get_directions$srceX$1$39({1}SC:U),B,1,4
S:Lmove_manager.engine_move_manager_get_directions$srceY$1$39({1}SC:U),B,1,5
S:Lmove_manager.engine_move_manager_get_directions$destX$1$39({1}SC:U),B,1,6
S:Lmove_manager.engine_move_manager_get_directions$destY$1$39({1}SC:U),B,1,7
S:Lmove_manager.engine_move_manager_get_directions$list$1$39({2}DG,SC:U),B,1,8
S:Lmove_manager.engine_move_manager_get_directions$half$1$39({2}DG,SC:U),B,1,10
S:Lmove_manager.engine_move_manager_get_directions$deltaX$1$40({1}SC:U),R,0,0,[b]
S:Lmove_manager.engine_move_manager_get_directions$deltaY$1$40({1}SC:U),R,0,0,[e]
S:Lmove_manager.engine_move_manager_get_directions$minusY$1$40({1}SC:U),R,0,0,[c]
S:Lmove_manager.engine_move_manager_get_directions$plusX$1$40({1}SC:U),B,1,-1
F:G$engine_move_manager_what_direction$0$0({2}DF,SC:U),Z,0,9,0,0,0
S:Lmove_manager.engine_move_manager_what_direction$sourceX$1$51({1}SC:U),B,1,4
S:Lmove_manager.engine_move_manager_what_direction$sourceY$1$51({1}SC:U),B,1,5
S:Lmove_manager.engine_move_manager_what_direction$prev_move$1$51({1}SC:U),B,1,6
S:Lmove_manager.engine_move_manager_what_direction$targetX$1$51({1}SC:U),B,1,7
S:Lmove_manager.engine_move_manager_what_direction$targetY$1$51({1}SC:U),B,1,8
S:Lmove_manager.engine_move_manager_what_direction$directions$1$52({4}DA4d,SC:U),B,1,-10
S:Lmove_manager.engine_move_manager_what_direction$move_direction$1$52({1}SC:U),B,1,-14
S:Lmove_manager.engine_move_manager_what_direction$oppX_direction$1$52({1}SC:U),B,1,-13
S:Lmove_manager.engine_move_manager_what_direction$test_direction$1$52({1}SC:U),R,0,0,[d]
S:Lmove_manager.engine_move_manager_what_direction$collision$1$52({1}SC:U),R,0,0,[]
S:Lmove_manager.engine_move_manager_what_direction$available$1$52({1}SC:U),B,1,-12
S:Lmove_manager.engine_move_manager_what_direction$index$1$52({1}SC:U),R,0,0,[e]
S:Lmove_manager.engine_move_manager_what_direction$list$1$52({1}SC:U),B,1,-11
S:Lmove_manager.engine_move_manager_what_direction$half$1$52({1}SC:U),B,1,-15
S:Lmove_manager.engine_move_manager_what_direction$flip$1$52({1}SC:U),R,0,0,[]
S:Lmove_manager.engine_move_manager_what_direction$sloc0$1$0({2}DD,SC:U),B,1,-2
S:Lmove_manager.engine_move_manager_what_direction$sloc1$1$0({2}DD,SC:U),B,1,-4
S:Lmove_manager.engine_move_manager_what_direction$sloc2$1$0({2}DD,SC:U),B,1,-6
F:G$engine_move_manager_gothru_exit$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lmove_manager.engine_move_manager_gothru_exit$tileX$1$58({1}SC:U),B,1,4
S:Lmove_manager.engine_move_manager_gothru_exit$tileY$1$58({1}SC:U),B,1,5
S:Lmove_manager.engine_move_manager_gothru_exit$direction$1$58({1}SC:U),B,1,6
S:Lmove_manager.engine_move_manager_gothru_exit$st$1$59({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lmove_manager.engine_move_manager_gothru_exit$can_go_thru_exit$1$59({1}SC:U),R,0,0,[l]
F:G$engine_move_manager_border_exit$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lmove_manager.engine_move_manager_border_exit$tileX$1$64({1}SC:U),B,1,4
S:Lmove_manager.engine_move_manager_border_exit$tileY$1$64({1}SC:U),B,1,5
S:Lmove_manager.engine_move_manager_border_exit$direction$1$64({1}SC:U),B,1,6
S:Lmove_manager.engine_move_manager_border_exit$can_go_thru_exit$1$65({1}SC:U),R,0,0,[l]
F:G$engine_move_manager_inside_exit$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lmove_manager.engine_move_manager_inside_exit$tileX$1$68({1}SC:U),B,1,4
S:Lmove_manager.engine_move_manager_inside_exit$tileY$1$68({1}SC:U),B,1,5
S:Lmove_manager.engine_move_manager_inside_exit$st$1$69({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lmove_manager.engine_move_manager_inside_exit$collision$1$69({1}SC:U),R,0,0,[c]
F:G$engine_move_manager_opposite_direction$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lmove_manager.engine_move_manager_opposite_direction$direction$1$75({1}SC:U),B,1,4
T:Fmove_manager$tag_struct_level_object[({0}S:S$level_object_bonus_count$0$0({1}SC:U),Z,0,0)({1}S:S$level_object_candy_count$0$0({1}SC:U),Z,0,0)({2}S:S$level_object_oneup_count$0$0({1}SC:U),Z,0,0)({3}S:S$level_object_multiplier$0$0({1}SC:U),Z,0,0)]
T:Fmove_manager$tag_struct_state_object[({0}S:S$state_object_availables$0$0({1}SC:U),Z,0,0)({1}S:S$state_object_localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$state_object_high_score$0$0({2}SI:U),Z,0,0)({4}S:S$state_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$state_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$state_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$state_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$state_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$state_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$state_object_actor_kill$0$0({1}SC:U),Z,0,0)({11}S:S$state_object_fight_type$0$0({1}SC:U),Z,0,0)({12}S:S$state_object_curr_screen$0$0({1}SC:U),Z,0,0)({13}S:S$state_object_next_screen$0$0({1}SC:U),Z,0,0)]
S:Fmove_manager$movement$0$0({4}DA4d,SC:U),E,0,0
S:G$level_object_tiles_array$0$0({0}DA0d,SC:U),E,0,0
S:G$global_level_object$0$0({4}STtag_struct_level_object:S),E,0,0
S:G$global_state_object$0$0({14}STtag_struct_state_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertXYtoZ$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertZtoXY$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertByteToNibbles$0$0({2}DF,SV:S),C,0,0
S:G$engine_function_manager_convertNibblesToByte$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_clear$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_load_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_temp_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_load_extra$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_directions$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_beat_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_blank_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_middle$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_get_collision$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_tile_type$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_next_tile$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_next_index$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_test_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_state_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_fight$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
