M:score_manager
F:G$engine_score_manager_text$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_text$text$1$38({2}DG,SC:U),R,0,0,[e,d]
S:Lscore_manager.engine_score_manager_text$index$1$38({1}SC:U),R,0,0,[c]
F:G$engine_score_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_init$so$1$41({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_init$st$1$41({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:G$engine_score_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_load$so$1$42({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_load$st$1$42({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:G$engine_score_manager_get_candy$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_get_candy$so$1$43({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_get_oneup$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_get_oneup$so$1$44({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_get_bonus$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_get_bonus$index$1$45({1}SC:U),B,1,4
F:G$engine_score_manager_get_value$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_get_value$index$1$47({1}SC:U),B,1,4
S:Lscore_manager.engine_score_manager_get_value$so$1$48({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_finish_bonus$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_finish_bonus$so$1$49({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_finish_bonus$bonus$1$49({1}SC:U),R,0,0,[b]
F:G$engine_score_manager_update_bonus$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_bonus$index$1$50({1}SC:U),B,1,4
S:Lscore_manager.engine_score_manager_update_bonus$so$1$51({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_update_bonus$lo$1$51({2}DG,STtag_struct_level_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_update_bonus$bonus$1$51({1}SC:U),R,0,0,[b]
F:G$engine_score_manager_update_candy$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_candy$so$1$52({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_update_oneup$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_oneup$so$1$53({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_update_lives$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_lives$value$1$54({1}SC:S),B,1,4
F:G$engine_score_manager_update_boost$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_boost$so$1$56({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_update_boost$st$1$56({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_update_boost$ho$1$56({2}DG,STtag_struct_hack_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_update_boost$sloc0$1$0({1}SC:U),B,1,-1
F:G$engine_score_manager_draw_init$0$0({2}DF,SV:S),C,0,0,0,0,0
F:G$engine_score_manager_draw_load$0$0({2}DF,SV:S),C,0,0,0,0,0
F:G$engine_score_manager_update_level$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_level$so$1$61({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_update_level$st$1$61({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:G$engine_score_manager_reset_lives$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_reset_lives$so$1$62({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_reset_lives$st$1$62({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:G$engine_score_manager_reset_boost$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_reset_boost$so$1$63({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_reset_boost$st$1$63({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:Fscore_manager$update_score$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.update_score$points$1$64({1}SC:U),B,1,4
S:Lscore_manager.update_score$so$1$65({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.update_score$st$1$65({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:Fscore_manager$update_lives$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.update_lives$value$1$68({1}SC:S),B,1,4
S:Lscore_manager.update_lives$so$1$69({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:Fscore_manager$draw_highs$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.draw_highs$st$1$72({2}DG,STtag_struct_state_object:S),R,0,0,[]
F:Fscore_manager$draw_score$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.draw_score$so$1$73({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:Fscore_manager$draw_value$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.draw_value$index$1$74({1}SC:U),B,1,4
S:Lscore_manager.draw_value$so$1$75({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.draw_value$st$1$75({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Lscore_manager.draw_value$y_val$1$75({1}SC:U),R,0,0,[c]
S:Lscore_manager.draw_value$value$1$75({1}SC:U),R,0,0,[e]
F:Fscore_manager$draw_zero$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.draw_zero$x$1$80({1}SC:U),B,1,4
S:Lscore_manager.draw_zero$y$1$80({1}SC:U),B,1,5
T:Fscore_manager$tag_struct_hack_object[({0}S:S$hack_object_delay_test$0$0({1}SC:U),Z,0,0)({1}S:S$hack_object_mydebugger$0$0({1}SC:U),Z,0,0)({2}S:S$hack_object_invincibie$0$0({1}SC:U),Z,0,0)({3}S:S$hack_object_full_boost$0$0({1}SC:U),Z,0,0)({4}S:S$hack_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$hack_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$hack_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$hack_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$hack_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$hack_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$hack_object_music_data$0$0({1}SC:U),Z,0,0)({11}S:S$hack_object_sound_data$0$0({1}SC:U),Z,0,0)({12}S:S$hack_object_enemy_move$0$0({3}DA3d,SC:U),Z,0,0)]
T:Fscore_manager$tag_struct_level_object[({0}S:S$level_object_bonus_count$0$0({1}SC:U),Z,0,0)({1}S:S$level_object_candy_count$0$0({1}SC:U),Z,0,0)({2}S:S$level_object_oneup_count$0$0({1}SC:U),Z,0,0)({3}S:S$level_object_multiplier$0$0({1}SC:U),Z,0,0)]
T:Fscore_manager$tag_struct_score_object[({0}S:S$score$0$0({2}SI:U),Z,0,0)({2}S:S$values$0$0({5}DA5d,SC:U),Z,0,0)({7}S:S$bonus$0$0({1}SC:U),Z,0,0)({8}S:S$candy$0$0({1}SC:U),Z,0,0)({9}S:S$oneup$0$0({1}SC:U),Z,0,0)]
T:Fscore_manager$tag_struct_state_object[({0}S:S$state_object_availables$0$0({1}SC:U),Z,0,0)({1}S:S$state_object_localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$state_object_high_score$0$0({2}SI:U),Z,0,0)({4}S:S$state_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$state_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$state_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$state_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$state_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$state_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$state_object_actor_kill$0$0({1}SC:U),Z,0,0)({11}S:S$state_object_fight_type$0$0({1}SC:U),Z,0,0)({12}S:S$state_object_curr_screen$0$0({1}SC:U),Z,0,0)({13}S:S$state_object_next_screen$0$0({1}SC:U),Z,0,0)]
S:Fscore_manager$bonuses$0$0({5}DA5d,SC:U),E,0,0
S:Fscore_manager$boost_X$0$0({2}DA2d,SC:U),E,0,0
S:Fscore_manager$value_y$0$0({5}DA5d,SC:U),E,0,0
S:Fscore_manager$title_Y$0$0({5}DA5d,SC:U),E,0,0
S:G$global_hack_object$0$0({15}STtag_struct_hack_object:S),E,0,0
S:G$level_object_tiles_array$0$0({0}DA0d,SC:U),E,0,0
S:G$global_level_object$0$0({4}STtag_struct_level_object:S),E,0,0
S:G$global_state_object$0$0({14}STtag_struct_state_object:S),E,0,0
S:G$locale_object_number$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$music_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_tiles$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$boss_object_color$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$locale_object_texts$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_AAdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$level_object_BBdata$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_score_object$0$0({10}STtag_struct_score_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_invert$0$0({2}DF,SV:S),C,0,0
S:G$engine_locale_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_clear$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_load_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_temp_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_load_extra$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_directions$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_beat_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_blank_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_middle$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_get_collision$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_tile_type$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_next_tile$0$0({2}DF,SC:U),C,0,0
S:G$engine_level_manager_get_next_index$0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_test_direction$0$0({2}DF,SC:U),C,0,0
S:G$engine_state_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_fight$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$engine_score_manager_draw_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_draw_load$0$0({2}DF,SV:S),C,0,0
