M:screen_manager
F:G$engine_screen_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscreen_manager.engine_screen_manager_init$open_screen_type$1$21({1}SC:U),B,1,4
F:G$engine_screen_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Fscreen_manager$curr_screen_type$0$0({1}SC:U),E,0,0
S:Fscreen_manager$next_screen_type$0$0({1}SC:U),E,0,0
S:Fscreen_manager$load_method$0$0({44}DA22d,DC,DF,SV:S),E,0,0
S:Fscreen_manager$update_method$0$0({44}DA22d,DC,DF,SV:S),E,0,0
S:G$screen_none_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_none_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_splash_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_splash_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_begin_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_begin_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_title_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_title_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_start_screen_init$0$0({2}DF,SV:S),C,0,0
S:G$screen_start_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_start_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_init_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_init_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_load_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_load_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_ready_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_ready_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_play_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_play_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_pass_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_pass_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_dead_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_dead_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_cont_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_cont_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_over_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_over_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_prep_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_prep_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_fight_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_fight_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_boss_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_boss_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_beat_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_beat_screen_update$0$0({2}DF,SV:S),C,0,0
S:G$screen_option_screen_init$0$0({2}DF,SV:S),C,0,0
S:G$screen_option_screen_load$0$0({2}DF,SV:S),C,0,0
S:G$screen_option_screen_update$0$0({2}DF,SV:S),C,0,0
