M:sprite_manager
F:G$engine_sprite_manager_draw_entity$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lsprite_manager.engine_sprite_manager_draw_entity$x$1$17({1}SC:U),B,1,4
S:Lsprite_manager.engine_sprite_manager_draw_entity$y$1$17({1}SC:U),B,1,5
S:Lsprite_manager.engine_sprite_manager_draw_entity$tile$1$17({2}SI:U),B,1,6
F:G$engine_sprite_manager_draw_boss1$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lsprite_manager.engine_sprite_manager_draw_boss1$x$1$19({1}SC:U),B,1,4
S:Lsprite_manager.engine_sprite_manager_draw_boss1$y$1$19({1}SC:U),B,1,5
S:Lsprite_manager.engine_sprite_manager_draw_boss1$tile$1$20({2}SI:U),R,0,0,[l,h]
S:Lsprite_manager.engine_sprite_manager_draw_boss1$row$1$20({1}SC:U),R,0,0,[c]
S:Lsprite_manager.engine_sprite_manager_draw_boss1$col$1$20({1}SC:U),R,0,0,[e]
S:Lsprite_manager.engine_sprite_manager_draw_boss1$sloc0$1$0({2}SI:S),B,1,-2
F:G$engine_sprite_manager_draw_boss2$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Lsprite_manager.engine_sprite_manager_draw_boss2$wide$1$25({1}SC:U),B,1,4
S:Lsprite_manager.engine_sprite_manager_draw_boss2$high$1$25({1}SC:U),B,1,5
S:Lsprite_manager.engine_sprite_manager_draw_boss2$x$1$25({1}SC:U),B,1,6
S:Lsprite_manager.engine_sprite_manager_draw_boss2$y$1$25({1}SC:U),B,1,7
S:Lsprite_manager.engine_sprite_manager_draw_boss2$tile$1$26({2}SI:U),R,0,0,[l,h]
S:Lsprite_manager.engine_sprite_manager_draw_boss2$row$1$26({1}SC:U),R,0,0,[c]
S:Lsprite_manager.engine_sprite_manager_draw_boss2$col$1$26({1}SC:U),R,0,0,[b]
S:Lsprite_manager.engine_sprite_manager_draw_boss2$top$1$26({1}SC:U),B,1,-5
S:Lsprite_manager.engine_sprite_manager_draw_boss2$lft$1$26({1}SC:U),B,1,-4
S:Lsprite_manager.engine_sprite_manager_draw_boss2$sloc0$1$0({1}SC:U),B,1,-1
S:Lsprite_manager.engine_sprite_manager_draw_boss2$sloc1$1$0({2}SI:S),B,1,-3
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
