M:timer_manager
F:G$engine_delay_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_delay_manager_load$delay$1$7({2}SI:U),B,1,4
S:Ltimer_manager.engine_delay_manager_load$dObj$1$8({2}DG,STtag_struct_delay_object:S),R,0,0,[]
S:Ltimer_manager.engine_delay_manager_load$st$1$8({2}DG,STtag_struct_state_object:S),R,0,0,[]
S:Ltimer_manager.engine_delay_manager_load$ho$1$8({2}DG,STtag_struct_hack_object:S),R,0,0,[]
F:G$engine_delay_manager_update$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Ltimer_manager.engine_delay_manager_update$dObj$1$10({2}DG,STtag_struct_delay_object:S),R,0,0,[]
S:Ltimer_manager.engine_delay_manager_update$test$1$10({1}SC:U),R,0,0,[b]
F:G$engine_delay_manager_draw$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_delay_manager_draw$dObj$1$12({2}DG,STtag_struct_delay_object:S),R,0,0,[]
F:G$engine_frame_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_frame_manager_load$fo$1$13({2}DG,STtag_struct_frame_object:S),R,0,0,[]
F:G$engine_frame_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_frame_manager_update$fo$1$14({2}DG,STtag_struct_frame_object:S),R,0,0,[]
F:G$engine_frame_manager_draw$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_frame_manager_draw$fo$1$16({2}DG,STtag_struct_frame_object:S),R,0,0,[]
F:G$engine_reset_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_reset_manager_load$delay$1$17({1}SC:U),B,1,4
S:Ltimer_manager.engine_reset_manager_load$ro$1$18({2}DG,STtag_struct_reset_object:S),R,0,0,[]
F:G$engine_reset_manager_update$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Ltimer_manager.engine_reset_manager_update$ro$1$19({2}DG,STtag_struct_reset_object:S),R,0,0,[]
S:Ltimer_manager.engine_reset_manager_update$test$1$19({1}SC:U),R,0,0,[d]
F:G$engine_reset_manager_reset$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_reset_manager_reset$ro$1$21({2}DG,STtag_struct_reset_object:S),R,0,0,[]
T:Ftimer_manager$tag_struct_hack_object[({0}S:S$hack_object_delay_test$0$0({1}SC:U),Z,0,0)({1}S:S$hack_object_mydebugger$0$0({1}SC:U),Z,0,0)({2}S:S$hack_object_invincibie$0$0({1}SC:U),Z,0,0)({3}S:S$hack_object_full_boost$0$0({1}SC:U),Z,0,0)({4}S:S$hack_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$hack_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$hack_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$hack_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$hack_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$hack_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$hack_object_music_data$0$0({1}SC:U),Z,0,0)({11}S:S$hack_object_sound_data$0$0({1}SC:U),Z,0,0)({12}S:S$hack_object_enemy_move$0$0({3}DA3d,SC:U),Z,0,0)]
T:Ftimer_manager$tag_struct_frame_object[({0}S:S$frame_count$0$0({2}SI:U),Z,0,0)]
T:Ftimer_manager$tag_struct_delay_object[({0}S:S$delay_value$0$0({2}SI:U),Z,0,0)({2}S:S$delay_timer$0$0({2}SI:U),Z,0,0)]
T:Ftimer_manager$tag_struct_state_object[({0}S:S$state_object_availables$0$0({1}SC:U),Z,0,0)({1}S:S$state_object_localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$state_object_high_score$0$0({2}SI:U),Z,0,0)({4}S:S$state_object_trees_type$0$0({1}SC:U),Z,0,0)({5}S:S$state_object_exits_type$0$0({1}SC:U),Z,0,0)({6}S:S$state_object_difficulty$0$0({1}SC:U),Z,0,0)({7}S:S$state_object_pace_speed$0$0({1}SC:U),Z,0,0)({8}S:S$state_object_world_data$0$0({1}SC:U),Z,0,0)({9}S:S$state_object_round_data$0$0({1}SC:U),Z,0,0)({10}S:S$state_object_actor_kill$0$0({1}SC:U),Z,0,0)({11}S:S$state_object_fight_type$0$0({1}SC:U),Z,0,0)({12}S:S$state_object_curr_screen$0$0({1}SC:U),Z,0,0)({13}S:S$state_object_next_screen$0$0({1}SC:U),Z,0,0)]
T:Ftimer_manager$tag_struct_reset_object[({0}S:S$reset_value$0$0({1}SC:U),Z,0,0)({1}S:S$reset_timer$0$0({1}SC:U),Z,0,0)]
S:G$global_hack_object$0$0({15}STtag_struct_hack_object:S),E,0,0
S:G$global_state_object$0$0({14}STtag_struct_state_object:S),E,0,0
S:G$global_delay_object$0$0({4}STtag_struct_delay_object:S),E,0,0
S:G$global_frame_object$0$0({2}STtag_struct_frame_object:S),E,0,0
S:G$global_reset_object$0$0({2}STtag_struct_reset_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_invert$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_state_manager_fight$0$0({2}DF,SV:S),C,0,0
